-- Add 'expired' to the ticket_status ENUM
ALTER TYPE public.ticket_status ADD VALUE 'expired';

-- Create Payments Table
CREATE TABLE public.payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    ticket_id bigint REFERENCES public.tickets(id) ON DELETE CASCADE,
    amount numeric NOT NULL,
    currency text NOT NULL,
    status text NOT NULL,
    payment_provider text,
    transaction_id text,
    UNIQUE(ticket_id)
);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own payments." ON public.payments FOR SELECT USING (
    (SELECT user_id FROM public.tickets WHERE id = ticket_id) = auth.uid()
);
CREATE POLICY "Organizers can view payments for their events." ON public.payments FOR SELECT USING (
    (SELECT organizer_id FROM public.events WHERE id = (SELECT event_id FROM public.tickets WHERE id = ticket_id)) = auth.uid()
);
